#### 107年01月~108年02月 0050 元大台灣50 各日成交資訊:
http://www.twse.com.tw/exchangeReport/STOCK_DAY?response=html&date=20180101&stockNo=0050
#### We need a list of date string in the date range we want.

In [13]:
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

start_date = "2018-01-01"
stop_date = "2019-02-01"

start = datetime.strptime(start_date, "%Y-%m-%d")
stop = datetime.strptime(stop_date, "%Y-%m-%d")

dates = list()
while start <= stop:
    dates.append(start.strftime('%Y%m%d'))
    start = start + relativedelta(months=1) #每次增加一個月
print(dates)

['20180101', '20180201', '20180301', '20180401', '20180501', '20180601', '20180701', '20180801', '20180901', '20181001', '20181101', '20181201', '20190101', '20190201']

#### Now write a function to parse the HTML response, return the data we want(title, content, ...etc).

In [14]:
import requests
from bs4 import BeautifulSoup as bs

In [17]:
def process_document(document, date):
    
    nodes = document.select('tbody > tr')
    data = list()

    for tr in nodes:
        nodes1 = tr.select('td')
         # append new row
        data.append({
            '日期' : nodes1[0].get_text(),
            '成交股數': nodes1[1].get_text(),
            '成交金額' : nodes1[2].get_text(),
            '開盤價' : nodes1[3].get_text(),
            '最高價' : nodes1[4].get_text(),
            '最低價' : nodes1[5].get_text(),
            '收盤價' : nodes1[6].get_text(),
            '漲跌價差' : nodes1[7].get_text(),
            '成交筆數' : nodes1[8].get_text(),
            
        })
            
        
    return data

#### Crawl over the news on the site, store the data in variable "all_data" .

In [18]:
cnt = 0
all_data = list()
for date in dates:
    print('start crawling :', date)
    res = requests.get('http://www.twse.com.tw/exchangeReport/STOCK_DAY?response=html&date='+date+'&stockNo=0050')
    doc = bs(res.text, 'lxml')
    data = process_document(doc, date)
    all_data += data

start crawling : 20180101
start crawling : 20180201
start crawling : 20180301
start crawling : 20180401
start crawling : 20180501
start crawling : 20180601
start crawling : 20180701
start crawling : 20180801
start crawling : 20180901
start crawling : 20181001
start crawling : 20181101
start crawling : 20181201
start crawling : 20190101
start crawling : 20190201

#### Check the result

In [19]:
all_data[0:5]

[{'成交筆數': '1,795',
  '成交股數': '3,613,199',
  '成交金額': '298,033,251',
  '收盤價': '82.60',
  '日期': '107/01/02',
  '最低價': '82.15',
  '最高價': '82.60',
  '漲跌價差': '+0.45',
  '開盤價': '82.15'},
 {'成交筆數': '3,014',
  '成交股數': '7,196,437',
  '成交金額': '599,476,413',
  '收盤價': '83.35',
  '日期': '107/01/03',
  '最低價': '82.95',
  '最高價': '83.45',
  '漲跌價差': '+0.75',
  '開盤價': '82.95'},
 {'成交筆數': '2,278',
  '成交股數': '5,627,565',
  '成交金額': '469,312,820',
  '收盤價': '83.50',
  '日期': '107/01/04',
  '最低價': '83.20',
  '最高價': '83.65',
  '漲跌價差': '+0.15',
  '開盤價': '83.50'},
 {'成交筆數': '2,562',
  '成交股數': '7,616,796',
  '成交金額': '636,768,692',
  '收盤價': '83.75',
  '日期': '107/01/05',
  '最低價': '83.30',
  '最高價': '83.80',
  '漲跌價差': '+0.25',
  '開盤價': '83.50'},
 {'成交筆數': '2,282',
  '成交股數': '5,189,611',
  '成交金額': '435,775,639',
  '收盤價': '84.10',
  '日期': '107/01/08',
  '最低價': '83.70',
  '最高價': '84.15',
  '漲跌價差': '+0.35',
  '開盤價': '83.80'}]

#### Save as pkl file

In [20]:
import pickle

with open('data/stock.pkl', 'wb') as f:
    pickle.dump(all_data, f)

#### Turn it into pandas dataframe

In [24]:
import pandas as pd
ETF50 = pd.DataFrame(all_data)[['日期', '成交股數', '成交金額', '開盤價', '最高價', '最低價', '收盤價', '漲跌價差', '成交筆數']]
ETF50.set_index("日期" , inplace=True)
ETF50

,成交股數,成交金額,開盤價,最高價,最低價,收盤價,漲跌價差,成交筆數
日期,,,,,,,,
107/01/02,"3,613,199","298,033,251",82.15,82.60,82.15,82.60,+0.45,"1,795"
107/01/03,"7,196,437","599,476,413",82.95,83.45,82.95,83.35,+0.75,"3,014"
107/01/04,"5,627,565","469,312,820",83.50,83.65,83.20,83.50,+0.15,"2,278"
107/01/05,"7,616,796","636,768,692",83.50,83.80,83.30,83.75,+0.25,"2,562"
107/01/08,"5,189,611","435,775,639",83.80,84.15,83.70,84.10,+0.35,"2,282"
107/01/09,"3,664,716","308,057,554",84.10,84.25,83.90,84.15,+0.05,"1,340"
107/01/10,"5,749,597","482,358,793",84.10,84.25,83.55,83.75,-0.40,"1,073"
107/01/11,"2,579,225","214,867,793",83.65,83.70,83.10,83.40,-0.35,735
107/01/12,"2,871,193","241,214,778",83.55,84.20,83.50,84.10,+0.70,"1,002"
107/01/15,"2,819,852","238,493,616",84.55,84.70,84.40,84.65,+0.55,"1,126"
107/01/16,"3,955,841","335,496,385",84.65,85.00,84.50,85.00,+0.35,"1,295"
107/01/17,"5,698,268","485,174,071",84.65,85.45,84.65,85.15,+0.15,"2,017"
107/01/18,"6,898,803","594,091,024",85.50,86.55,85.50,86.30,+1.15,"2,272"
107/01/19,"5,302,072","461,040,360",86.35,87.15,86.35,87.15,+0.85,"1,445"
107/01/22,"4,441,061","389,066,253",87.15,87.95,87.15,87.95,+0.80,"1,746"
107/01/23,"5,799,932","511,405,502",88.05,88.40,87.90,88.30,+0.35,"1,842"
107/01/24,"5,103,429","444,907,065",88.00,88.00,86.85,87.20,-1.10,"1,869"
107/01/25,"4,983,684","436,967,956",87.25,88.30,87.15,87.45,+0.25,"1,652"
107/01/26,"7,774,673","678,481,509",87.45,87.60,86.85,87.50,+0.05,"3,087"
107/01/29,"6,445,797","551,350,942",85.50,86.15,85.20,85.55,X0.00,"3,453"
107/01/30,"4,966,261","421,572,779",85.20,85.35,84.50,84.55,-1.00,"2,337"
107/01/31,"4,251,739","359,040,915",84.40,85.00,84.15,84.65,+0.10,"1,176"
107/10/01,"5,914,234","516,131,207",86.90,87.40,86.90,87.35,+0.45,"2,729"
107/10/02,"5,434,332","469,382,289",87.25,87.25,86.00,86.05,-1.30,"2,466"
107/10/03,"4,369,690","375,778,640",86.05,86.30,85.80,85.95,-0.10,"1,554"
107/10/04,"9,736,968","827,292,110",85.70,85.70,84.80,84.90,-1.05,"4,230"
107/10/05,"26,744,096","2,239,942,717",84.50,84.50,83.00,83.45,-1.45,"11,367"
107/10/08,"46,523,204","3,855,479,629",82.95,83.40,82.50,83.00,-0.45,"16,777"
107/10/09,"20,530,897","1,706,528,887",83.05,83.40,82.80,83.25,+0.25,"9,093"
107/10/11,"68,551,624","5,389,808,235",80.15,80.15,77.35,77.40,-5.85,"29,625"
...,...,...,...,...,...,...,...,...
108/01/08,"11,006,700","811,364,720",74.15,74.15,73.55,73.65,-0.30,"2,869"
108/01/09,"11,430,523","855,269,355",73.95,75.15,73.95,75.00,+1.35,"5,277"
108/01/10,"2,823,283","210,937,625",74.80,74.90,74.50,74.80,-0.20,"1,231"
108/01/11,"10,362,915","782,200,792",75.30,75.75,75.15,75.50,+0.70,"3,660"
108/01/14,"5,298,405","397,504,723",75.45,75.45,74.75,75.00,-0.50,"2,018"
108/01/15,"11,836,450","894,286,699",75.05,75.80,75.05,75.65,+0.65,"5,250"
108/01/16,"15,342,503","1,159,613,447",75.65,75.70,75.35,75.55,-0.10,"5,360"
108/01/17,"10,020,739","756,877,394",75.60,75.90,75.15,75.55,0.00,"3,137"
108/01/18,"8,293,491","629,378,860",75.75,76.10,75.40,75.95,+0.40,"5,013"
108/01/21,"10,454,756","799,923,534",76.35,76.70,76.25,76.50,+0.55,"3,895"
108/01/22,"8,838,931","653,814,320",74.40,74.40,73.80,74.05,X0.00,"4,742"
108/01/23,"6,407,442","472,728,408",74.00,74.00,73.65,73.70,-0.35,"3,167"
108/01/24,"3,500,506","258,832,935",73.95,74.15,73.75,74.05,+0.35,"1,363"
108/01/25,"7,320,778","548,115,919",74.60,75.10,74.55,75.00,+0.95,"3,322"
108/01/28,"3,825,143","287,814,225",75.15,75.45,75.05,75.15,+0.15,"1,795"
108/01/29,"4,419,790","328,663,492",74.50,74.55,74.20,74.50,-0.65,"2,251"
108/01/30,"5,255,229","390,864,071",74.50,74.65,74.20,74.35,-0.15,"1,833"
108/02/11,"6,614,900","497,844,612",75.35,75.65,74.85,75.15,+0.80,"3,137"
108/02/12,"6,164,150","465,816,739",75.35,75.75,75.35,75.65,+0.50,"2,980"
108/02/13,"4,157,700","314,193,830",75.95,75.95,75.40,75.50,-0.15,"1,837"
108/02/14,"3,641,542","274,887,735",75.50,75.75,75.25,75.25,-0.25,"1,593"
108/02/15,"3,516,111","264,409,753",75.30,75.60,74.90,75.05,-0.20,"1,796"
108/02/18,"6,596,163","499,575,240",75.50,75.90,75.50,75.65,+0.60,"3,143"
108/02/19,"2,862,069","216,303,714",75.70,75.70,75.50,75.50,-0.15,"2,168"
108/02/20,"34,307,853","2,619,961,938",75.90,76.50,75.90,76.35,+0.85,"9,607"
108/02/21,"18,664,815","1,433,791,393",76.40,77.10,76.40,77.10,+0.75,"4,467"
108/02/22,"9,881,017","758,887,009",76.95,76.95,76.50,76.95,-0.15,"6,936"
108/02/25,"19,365,354","1,501,862,131",77.35,77.75,77.30,77.50,+0.55,"4,458"
108/02/26,"15,903,051","1,234,156,605",77.65,77.80,77.30,77.70,+0.20,"5,707"
108/02/27,"12,907,489","1,000,792,293",77.70,77.70,77.35,77.65,-0.05,"3,460"